name: todolist_riverpod_firebase2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod:
  riverpod_annotation:
  freezed_annotation:
  firebase_core:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator:
  freezed:


flutter:


  uses-material-design: true

